/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author work-
 */
public class Frame_Gerente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frame_funcionario
     */
    public Frame_Gerente() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_birthday = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jText_id = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jText_cliente = new javax.swing.JTextField();
        jText_terreno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_inserir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jText_cpf = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_selecionar = new javax.swing.JButton();
        jText_foto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jText_nome1 = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
        jPanel1.add(jText_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 216, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 169, 37));

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "TERRENO", "STATUS", "ANIVERSARIO"
            }
        ));
        jScrollPane1.setViewportView(tabelaCliente);
        if (tabelaCliente.getColumnModel().getColumnCount() > 0) {
            tabelaCliente.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 700, 367));
        jPanel1.add(jText_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 103, -1));

        jLabel26.setText("ID: ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(jText_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 244, -1));
        jPanel1.add(jText_terreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 244, -1));

        jLabel4.setText("Terreno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Cliente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jButton_inserir.setText("Inserir dados");
        jButton_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inserirActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel6.setText("DATA DE NASCIMENTO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel7.setText("CPF:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        try {
            jText_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jText_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 220, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Foto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 150));

        jButton_selecionar.setText("SELECIONAR");
        jPanel1.add(jButton_selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
        jPanel1.add(jText_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 230, -1));

        jButton1.setText("Carregar campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 140, -1));
        jPanel1.add(jText_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 216, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carregacampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inserirActionPerformed
        AlterarCliente();
        limpar();
    }//GEN-LAST:event_jButton_inserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_inserir;
    private javax.swing.JButton jButton_selecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jText_birthday;
    private javax.swing.JTextField jText_cliente;
    private javax.swing.JFormattedTextField jText_cpf;
    private javax.swing.JTextField jText_foto;
    private javax.swing.JTextField jText_id;
    private javax.swing.JTextField jText_nome1;
    private javax.swing.JTextField jText_terreno;
    private javax.swing.JTable tabelaCliente;
    // End of variables declaration//GEN-END:variables
    public void AlterarCliente() {
        int id;
        String birthday, cpf, foto;

        id = Integer.parseInt(jText_id.getText());
        birthday = jText_birthday.getText();
        cpf = jText_cpf.getText();
        foto = jText_foto.getText();

        Cliente cliente = new Cliente();
        cliente.setId(id);
        cliente.setBirthday(birthday);
        cliente.setCpf(cpf);
        cliente.setFoto(foto);

        ClienteDAO dao = new ClienteDAO();
        dao.alterar(cliente);

        listarValores();
    }

    private void listarValores() {
        try {
            ClienteDAO dao = new ClienteDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaCliente.getModel();
            model.setNumRows(0);

            ArrayList<Cliente> lista = dao.readgerente();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getName(),
                    lista.get(num).getTerreno(),
                    lista.get(num).getStatus(),
                    lista.get(num).getBirthday(),
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar Valores, Frame gerente erro:" + erro);
        }
    }

    private void limpar() {
        jText_birthday.setText("");
        jText_id.setText("");
        jText_cliente.setText("");
        jText_terreno.setText("");
    }

    private void carregacampos() {

        int linha = tabelaCliente.getSelectedRow();

        jText_id.setText(tabelaCliente.getModel().getValueAt(linha, 0).toString());
        jText_cliente.setText(tabelaCliente.getModel().getValueAt(linha, 1).toString());
        jText_terreno.setText(tabelaCliente.getModel().getValueAt(linha, 2).toString());
    }
}
