/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.bean.Funcionario;
import model.dao.FuncionarioDAO;

/**
 *
 * @author work-
 */
public class FrameInt_Excluir extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameInt_Cadastro
     */
    public FrameInt_Excluir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_cargo = new javax.swing.JLabel();
        jLabel_Biometria = new javax.swing.JLabel();
        jLabel_foto = new javax.swing.JLabel();
        jButton_Selecionar = new javax.swing.JButton();
        jButton_Confirmar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Cargo = new javax.swing.JComboBox<>();
        JText_field_CPF = new javax.swing.JFormattedTextField();
        jTextField_Nasc = new javax.swing.JFormattedTextField();

        jButton4.setText("jButton4");

        jLabel3.setText("jLabel3");

        setClosable(true);
        setTitle("Excluir");
        setMinimumSize(new java.awt.Dimension(847, 623));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nome.setText("NOME:");
        getContentPane().add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel_cargo.setText("CARGO:");
        getContentPane().add(jLabel_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 374, -1, -1));

        jLabel_Biometria.setText("BIOMETRIA:");
        getContentPane().add(jLabel_Biometria, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 449, -1, -1));

        jLabel_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 240, 230));

        jButton_Selecionar.setText("SELECIONAR");
        jButton_Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 198, -1, -1));

        jButton_Confirmar.setText("CONFIRMAR");
        jButton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 650, -1, -1));

        jButton_Cancelar.setText("CANCELAR");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, -1));
        getContentPane().add(jTextField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 428, -1));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setText("LOGO");
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 36, 198, 150));

        jLabel1.setText("DATA DE NASCIMENTO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 374, -1, -1));

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jComboBox_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNCIONÁRIO", "GERENTE", "DIRETOR" }));
        getContentPane().add(jComboBox_Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 371, 212, -1));

        try {
            JText_field_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(JText_field_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, -1));

        try {
            jTextField_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField_Nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NascActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
       dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarActionPerformed
        FuncionarioDAO funcionario = new FuncionarioDAO();
        funcionario.excluir(JText_field_CPF.getText());
        jTextField_Nome.setText("");
        jTextField_Nasc.setText("");
        jComboBox_Cargo.setToolTipText("");
        ImageIcon usu = new ImageIcon("src\\Fotos_software\\Photousuario.jpg");
        Image img = usu.getImage();
        Image imgRedimensionada = img.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        ImageIcon usu_red = new ImageIcon (imgRedimensionada);
        jLabel_foto.setIcon(usu_red);
        JText_field_CPF.setText("");
    }//GEN-LAST:event_jButton_ConfirmarActionPerformed

    private void jButton_SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarActionPerformed
        FuncionarioDAO dao = new FuncionarioDAO();
        Funcionario fm = new Funcionario();
        fm = dao.read(JText_field_CPF.getText());
        jTextField_Nome.setText(fm.getName());
        jTextField_Nasc.setText(fm.getBirthday());
        jComboBox_Cargo.setToolTipText(fm.getCargo());
        ImageIcon usu = new ImageIcon(fm.getFoto());
        Image img = usu.getImage();
        Image imgRedimensionada = img.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        ImageIcon usu_red = new ImageIcon (imgRedimensionada);
        jLabel_foto.setIcon(usu_red);
    }//GEN-LAST:event_jButton_SelecionarActionPerformed

    private void jTextField_NascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NascActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JText_field_CPF;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JButton jButton_Selecionar;
    private javax.swing.JComboBox<String> jComboBox_Cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Biometria;
    private javax.swing.JLabel jLabel_cargo;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JFormattedTextField jTextField_Nasc;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
