/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Conection.ConnectionFactory;
import javax.swing.ImageIcon;
import Reconhecimento.CapturaFoto;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.bean.Funcionario;
import model.dao.FuncionarioDAO;
import org.bytedeco.javacv.FrameGrabber;
import java.awt.event.KeyEvent;
import org.bytedeco.javacpp.opencv_core.Mat;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.OpenCVFrameConverter;
import org.bytedeco.javacv.OpenCVFrameGrabber;

/**
 *
 * @author work-
 */
public class FrameInt_Cadastro extends javax.swing.JInternalFrame {
        
        String cam = ("src\\Fotos_software\\Photousuario.jpg");
        ImageIcon usu = new ImageIcon(cam);
        Image img = usu.getImage();
        Image imgRedimensionada = img.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        ImageIcon usu_red = new ImageIcon (imgRedimensionada);
        
    public FrameInt_Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_cargo = new javax.swing.JLabel();
        jLabel_Biometria = new javax.swing.JLabel();
        jLabel_foto = new javax.swing.JLabel();
        jButton_Selecionar = new javax.swing.JButton();
        jButton_Confirmar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Cargo = new javax.swing.JComboBox<>();
        jTextField_foto = new javax.swing.JTextField();
        jTextField_cpf = new javax.swing.JFormattedTextField();
        jTextField_birthday = new javax.swing.JFormattedTextField();

        jButton4.setText("jButton4");

        jLabel3.setText("jLabel3");

        setClosable(true);
        setTitle("Cadastro");
        setMinimumSize(new java.awt.Dimension(847, 623));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nome.setText("NOME:");
        getContentPane().add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel_cargo.setText("CARGO:");
        getContentPane().add(jLabel_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel_Biometria.setText("BIOMETRIA:");
        getContentPane().add(jLabel_Biometria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 350, 310));

        jButton_Selecionar.setText("TIRAR FOTO");
        jButton_Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jButton_Confirmar.setText("CONFIRMAR");
        jButton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        jButton_Cancelar.setText("CANCELAR");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));
        getContentPane().add(jTextField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 428, -1));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setText("LOGO");
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, 198, 150));

        jLabel1.setText("DATA DE NASCIMENTO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jComboBox_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNCIONÁRIO", "GERENTE", "DIRETOR" }));
        getContentPane().add(jComboBox_Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 212, -1));
        getContentPane().add(jTextField_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 225, -1));

        try {
            jTextField_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTextField_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 220, -1));

        try {
            jTextField_birthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTextField_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarActionPerformed

        FuncionarioDAO dao = new FuncionarioDAO();
        Funcionario f = new Funcionario();

        f.setName(jTextField_Nome.getText());
        f.setBirthday(jTextField_birthday.getText());
        f.setCpf(jTextField_cpf.getText());
        f.setFoto(jTextField_foto.getText());
        f.setCargo(jComboBox_Cargo.getToolTipText());
        dao.create(f);
        
        jTextField_Nome.setText("");
        jTextField_birthday.setText("");
        jTextField_cpf.setText("");
        jTextField_foto.setText("");
        jComboBox_Cargo.setToolTipText("");
        jLabel_foto.setIcon(usu_red);
        
    }//GEN-LAST:event_jButton_ConfirmarActionPerformed

    private void jButton_SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarActionPerformed
        String fun = jTextField_cpf.getText();
        Frame framecapturado = null;
        CapturaFoto cm = new CapturaFoto();
           
        try {
            cm.CameraInicia(fun);
        } catch (FrameGrabber.Exception ex) {
            Logger.getLogger(FrameInt_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrameInt_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        String cam = "src\\fotos\\pessoa."+fun+".1.jpg";
        ImageIcon imagem = new ImageIcon(cam);
        jTextField_foto.setText(cam);
        jLabel_foto.setIcon(imagem);
    }//GEN-LAST:event_jButton_SelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JButton jButton_Selecionar;
    private javax.swing.JComboBox<String> jComboBox_Cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Biometria;
    private javax.swing.JLabel jLabel_cargo;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JFormattedTextField jTextField_birthday;
    private javax.swing.JFormattedTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_foto;
    // End of variables declaration//GEN-END:variables
}
